name: Bug Report
description: Report a UNS-1 Bug
title: ""
labels: ["q4xp integration", "bug"]
assignees:
  - amyinorbit
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: |
        How can we get in touch with you if we need more info?
        (leave empty if you prefer using GitHub issues to communicate)
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the UNS-1 plugin are you using?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: >
        Tell us what happened: what the FMS did, what you expected it to do instead,
        and any information you think might be relevant or help us reproduce the bug.
        *PLEASE ATTACH YOUR LOG FILE* 
      placeholder:
      value: "# What happened
        
        
        # Expected behaviour
        
        
        # Attach your log file here"
        
    validations:
      required: true
