name: Bug Report
description: Report a UNS-1 Bug
title: "[Q4XP]: "
labels: ["q4xp integration", "bug"]
assignees:
  - amyinorbit
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: |
        How can we get in touch with you if we need more info?
        (leave empty if you prefer using GitHub issues to communicate)
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Please give us as much information as possible about what happened, and what you
        expected to happen
      placeholder: Tell us what you see!
      value: "The UNS-1 took me to the Bermuda Triangle instead of Heathrow."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the UNS-1 plugin are you using?
    validations:
      required: true
